version: "3.8"

services:
  app:
    build: ./
    ports:
      - "8080:8080"
    environment:
      DB_IP: db
      DB_NAME: learning_center_management_full
      DB_PASSWORD: 1
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 1
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: learning_center_management_full
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
#

