version: "3.8"

services:
  app:
    build: ./
    ports:
      - "8081:8083"
    environment:
      DB_IP: db
      DB_NAME: postgres
      DB_PASSWORD: 1
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 1
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: learning_center_db
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:


